FROM ubuntu
RUN apt-get update && apt-get install -y software-properties-common && add-apt-repository -y ppa:linuxuprising/java && echo "yes" | apt-get install --yes oracle-java10-installer && apt-get install -y oracle-java10-set-default
